### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by micheleberrettis1** [Moyster/android_kernel_m2note#14]
LD      drivers/usb/storage/usb-storage.o
  LD      drivers/usb/storage/ums-alauda.o
  LD      drivers/usb/storage/ums-cypress.o
  LD      drivers/usb/storage/ums-datafab.o
  LD      drivers/usb/storage/ums-freecom.o
  LD      drivers/usb/storage/ums-isd200.o
  LD      drivers/usb/storage/ums-jumpshot.o
  LD      drivers/usb/storage/ums-karma.o
  LD      drivers/usb/storage/ums-onetouch.o
  LD      drivers/usb/storage/ums-sddr09.o
  LD      drivers/usb/storage/ums-sddr55.o
  LD      drivers/usb/storage/ums-usbat.o
  LD      drivers/usb/storage/built-in.o
  LD      drivers/usb/built-in.o
make: *** [Makefile:827: drivers] Error 2

Getting this error when executing " make m2note_defconfig " and then " make -j5 "...
Any help?

Wanted to build Kali Nethunter but can't get the Image.gz-dtb that i need...

**Comment by micheleberrettis1** [comment]
After executing " make headers_check " and " make headers_install " and " make scripts " i get:

/home/mib/kali3/android_kernel_m2note/arch/arm64/include/asm/memory.h:99:0: note: this is the location of the previous definition
 #define PHYS_OFFSET  ({ memstart_addr; })
 ^
drivers/misc/mediatek/mmc-host/mt6735/sd.c: In function 'emmc_clear_timing':
drivers/misc/mediatek/mmc-host/mt6735/sd.c:6406:11: warning: unused variable 'base' [-Wunused-variable]
     void __iomem *base = 0;
           ^
drivers/misc/mediatek/mmc-host/mt6735/sd.c:6405:16: warning: unused variable 'err' [-Wunused-variable]
     int i = 0, err = 0;
                ^
drivers/misc/mediatek/mmc-host/mt6735/sd.c: At top level:
drivers/misc/mediatek/mmc-host/mt6735/sd.c:6403:13: warning: 'emmc_clear_timing' defined but not used [-Wunused-function]
 static void emmc_clear_timing(void)
             ^
  LD      drivers/misc/mediatek/mmc-host/mt6735/built-in.o
  LD      drivers/misc/mediatek/mmc-host/built-in.o
make[2]: *** [scripts/Makefile.build:455: drivers/misc/mediatek] Error 2
make[1]: *** [scripts/Makefile.build:455: drivers/misc] Error 2
make: *** [Makefile:827: drivers] Error 2

Been looking for something like mmc host  in drivers/misc/mediatek when executing " make menuconfig " but i found nothing...

**Comment by Moyster** [comment]
Are you building inside android sources or out-of-tree ?
In any case you don't have to trouble yourself with make commands.  
M2note defconfig is in arch/arm64/configs/m2note_defconfig, edit your kernel configuration from there better than make menuconfig / how you'd build a linux kernel.

Your error (even tho the log is pretty incomplete) doesn't really come from mediatek's mmc-host driver, unless you didn't properly apply NetHunter patches.  
Start with a fresh copy of my kernel sources, compile it to make sure you can compile code, then apply your NetHunter modifications > build/fix/build/whatever ;)

**Comment by micheleberrettis1** [comment]
I'm building out of tree, i'll try now with a fresh start!

**Comment by micheleberrettis1** [comment]
Getting Error2 for driver/misc/mediatek/m4u
