### ISSUE TITLE
musb error

### ISSUE THREAD

**Issue by micheleberrettis1** [Moyster/android_kernel_m2note#18]
drivers/built-in.o: In function `musb_gadget_enable':
/home/mib/sugo/android_kernel_m2note/drivers/misc/mediatek/usb20/musb_gadget.c:1743: undefined reference to `bitdebug_enabled'
/home/mib/sugo/android_kernel_m2note/drivers/misc/mediatek/usb20/musb_gadget.c:1743: undefined reference to `bitdebug_enabled'
drivers/built-in.o: In function `adbDbgInfoCheck':
/home/mib/sugo/android_kernel_m2note/drivers/misc/mediatek/usb20/musb_gadget.c:275: undefined reference to `bitdebug_writeCnt'
/home/mib/sugo/android_kernel_m2note/drivers/misc/mediatek/usb20/musb_gadget.c:275: undefined reference to `bitdebug_writeCnt'
/home/mib/sugo/android_kernel_m2note/drivers/misc/mediatek/usb20/musb_gadget.c:278: undefined reference to `bitdebug_writeCnt'
/home/mib/sugo/android_kernel_m2note/drivers/misc/mediatek/usb20/musb_gadget.c:276: undefined reference to `bitdebug_writeCnt'
drivers/built-in.o: In function `musb_g_giveback':
/home/mib/sugo/android_kernel_m2note/drivers/misc/mediatek/usb20/musb_gadget.c:566: undefined reference to `bitdebug_enabled'
/home/mib/sugo/android_kernel_m2note/drivers/misc/mediatek/usb20/musb_gadget.c:566: undefined reference to `bitdebug_enabled'
/home/mib/sugo/android_kernel_m2note/drivers/misc/mediatek/usb20/musb_gadget.c:566: undefined reference to `bitdebug_enabled'
/home/mib/sugo/android_kernel_m2note/drivers/misc/mediatek/usb20/musb_gadget.c:566: undefined reference to `bitdebug_enabled'
drivers/built-in.o: In function `adbDebugInfoWrite':
/home/mib/sugo/android_kernel_m2note/drivers/misc/mediatek/usb20/musb_gadget.c:300: undefined reference to `ep_in'
/home/mib/sugo/android_kernel_m2note/drivers/misc/mediatek/usb20/musb_gadget.c:300: undefined reference to `ep_in'
drivers/built-in.o: In function `musb_gadget_queue':
/home/mib/sugo/android_kernel_m2note/drivers/misc/mediatek/usb20/musb_gadget.c:2073: undefined reference to `bitdebug_enabled'
/home/mib/sugo/android_kernel_m2note/drivers/misc/mediatek/usb20/musb_gadget.c:2073: undefined reference to `bitdebug_enabled'
drivers/built-in.o: In function `adbDegInfoHandle':
/home/mib/sugo/android_kernel_m2note/drivers/misc/mediatek/usb20/musb_gadget.c:398: undefined reference to `ep_in'
/home/mib/sugo/android_kernel_m2note/drivers/misc/mediatek/usb20/musb_gadget.c:398: undefined reference to `ep_in'
/home/mib/sugo/android_kernel_m2note/drivers/misc/mediatek/usb20/musb_gadget.c:382: undefined reference to `ep_out'
/home/mib/sugo/android_kernel_m2note/drivers/misc/mediatek/usb20/musb_gadget.c:382: undefined reference to `ep_out'
/home/mib/sugo/android_kernel_m2note/drivers/misc/mediatek/usb20/musb_gadget.c:390: undefined reference to `bitdebug_readCnt'
/home/mib/sugo/android_kernel_m2note/drivers/misc/mediatek/usb20/musb_gadget.c:390: undefined reference to `bitdebug_readCnt'
/home/mib/sugo/android_kernel_m2note/drivers/misc/mediatek/usb20/musb_gadget.c:390: undefined reference to `bitdebug_readCnt'
drivers/built-in.o: In function `txstate':
/home/mib/sugo/android_kernel_m2note/drivers/misc/mediatek/usb20/musb_gadget.c:779: undefined reference to `bitdebug_enabled'
/home/mib/sugo/android_kernel_m2note/drivers/misc/mediatek/usb20/musb_gadget.c:779: undefined reference to `bitdebug_enabled'
/home/mib/sugo/android_kernel_m2note/drivers/misc/mediatek/usb20/musb_gadget.c:780: undefined reference to `ep_in'
/home/mib/sugo/android_kernel_m2note/drivers/misc/mediatek/usb20/musb_gadget.c:780: undefined reference to `ep_in'
drivers/built-in.o: In function `musb_g_rx':
/home/mib/sugo/android_kernel_m2note/drivers/misc/mediatek/usb20/musb_gadget.c:1449: undefined reference to `bitdebug_enabled'
/home/mib/sugo/android_kernel_m2note/drivers/misc/mediatek/usb20/musb_gadget.c:1449: undefined reference to `bitdebug_enabled'
drivers/built-in.o: In function `rxstate':
/home/mib/sugo/android_kernel_m2note/drivers/misc/mediatek/usb20/musb_gadget.c:1239: undefined reference to `bitdebug_enabled'
/home/mib/sugo/android_kernel_m2note/drivers/misc/mediatek/usb20/musb_gadget.c:1239: undefined reference to `bitdebug_enabled'
drivers/built-in.o: In function `musb_g_rx':
/home/mib/sugo/android_kernel_m2note/drivers/misc/mediatek/usb20/musb_gadget.c:1450: undefined reference to `ep_out'
/home/mib/sugo/android_kernel_m2note/drivers/misc/mediatek/usb20/musb_gadget.c:1450: undefined reference to `ep_out'
drivers/built-in.o: In function `rxstate':
/home/mib/sugo/android_kernel_m2note/drivers/misc/mediatek/usb20/musb_gadget.c:1240: undefined reference to `ep_out'
/home/mib/sugo/android_kernel_m2note/drivers/misc/mediatek/usb20/musb_gadget.c:1240: undefined reference to `ep_out'
make: *** [Makefile:813: vmlinux] Error 1

getting this error... please help

**Comment by Moyster** [comment]
I'm not Meizu, I keep this kernel maintained and updated for my own projects, I know the kernel builds/boot/work for Android N & O, so if you have "issues" because you do modifications or try to apply NetHunters patches, it's on you.  

I'm gonna close this because I'm not providing build assistance to "not my stuff", as a hint tho, I'm pretty sure you don't clean your out/ or that the nethunter patches weren't properly applied.  

Good luck
