### ISSUE TITLE
Problem while compiling 

### ISSUE THREAD

**Issue by aufabdulnafea** [Moyster/android_kernel_m2note#24]
I have tried to compile the kernel using this Command

> make -j9 bootimage

but the result is always like this.

> _/root/Desktop/meizu/android_kernel_m2note/arch/x86/Makefile:96: stack-protector enabled but compiler support broken
Makefile:625: Cannot use CONFIG_CC_STACKPROTECTOR_STRONG: -fstack-protector-strong not supported by compiler
make: *** No rule to make target 'bootimage'.  Stop._

**Comment by Moyster** [comment]
You need to use an arm64 compiler/toolchain, google will help about how to properly do that ;)

**Comment by aufabdulnafea** [comment]
I have already tried to do that and still getting this message 

> make: *** No rule to make target 'bootimage'. Stop.
